name: darvel
description: A Laravel-like framework in Dart.
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  shelf_router_generator: ^1.1.1
  get_it: ^8.0.3
  envied: ^1.1.1
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.18 # You can change this to postgres if needed
  args: ^2.4.2
  mustache_template: ^2.0.0
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.6
  source_gen: ^1.4.0

executables:
  darvel: cli
